# Agustin Wisky <a.wisky@patagon.io> 

version: '3'
services:
  bot:
    build: .
    environment:
      - DEBUG=true
      - SHELL=/bin/bash
      - PG_HOST=pgbouncer
      - PG_PORT=5432
      - PG_DB=taxengine
      - PG_USER=taxengine
      - PG_PASSWORD=taxengine
      - TABLE_NAME=importacion_exclusiones
      - COMMAND=init # use jupyter to start jupyter lab and run the app from there
      - JUPYTER_TOKEN=the5ooxoo0ahNoojuNgiahoon8koozie
      - CREATE=true # This variable is only necessary for local development
      - OUTPUT_PATH=/code/app/downloads
      - ODOO_URL=https://tax-engine-backend-jx-staging.c3xsrv.com/jsonrpc
      - ODOO_USER=admin
      - ODOO_PASSWORD=vae9Bahraibooyiecisai5jam6pei8Uc
      - ODOO_DB=tax-engine-backend
      - ODOO_DIRECTORY_TO_PROCESS=42 # carpeta "dia-clientes\Para procesar"
      - ODOO_DIRECTORY_PROCESSED=43 # carpeta "dia-clientes\Procesados"
    ports:
      - "1022:22"
      - "3002:3002" # Debugpy if Debug=true | Matching the .vscode launch "debugServer": 3002 
      - "8888:8888"
    tty: true
    volumes:
      - ./:/code
networks:
  default:
      external:
        name: tax-engine-database_default
