# Agustin Wisky <a.wisky@patagon.io> 

version: '3'
services:
  bot:
    build: .
    environment:
      - DEBUG=True
      - SHELL=/bin/bash
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=taxengine
      - PG_USER=taxengine
      - PG_PASSWORD=taxengine
      - RETRO=1
      - COMMAND=init # use jupyter to start jupyter lab and run the app from there
      - JUPYTER_TOKEN=the5ooxoo0ahNoojuNgiahoon8koozie
      - CREATE=true # This variable is only necessary for local development
      - OUTPUT_PATH=/code/app/downloads
      - ODOO_URL=https://tax-engine-backend-jx-staging.c3xsrv.com/jsonrpc
      - ODOO_USER=admin
      - ODOO_PASSWORD=vae9Bahraibooyiecisai5jam6pei8Uc
      - ODOO_DB=tax-engine-backend
      - ODOO_DIRECTORY_TO_PROCESS=21 # carpeta "dia-clientes\Para procesar"
      - ODOO_DIRECTORY_PROCESSED=22 # carpeta "dia-clientes\Procesados"
    depends_on:
      - db
    ports:
      - "1022:22"
      - "3002:3002" # Debugpy if Debug=true | Matching the .vscode launch "debugServer": 3002 
      - "8888:8888"
    tty: true
    volumes:
      - ./:/code
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=taxengine
      - POSTGRES_USER=taxengine
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - bot-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:6.2
    entrypoint: >
      /bin/sh -c "
      chmod 600 /pgadmin4/pgpass;
      chown pgadmin:pgadmin /pgadmin4/pgpass;
      cp -afr /pgadmin4/pgpass /var/lib/pgadmin/;
      /entrypoint.sh
      "
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@c3xsrv.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8098:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json 
      - ./pgadmin/pgpass:/pgadmin4/pgpass
volumes:
  bot-db-data:
  pgadmin-data:
