services:
  bot:
    build: .
    environment:
      - DEBUG=true
      - SHELL=/bin/bash
      - PG_HOST=c3xsrv-staging-cluster.cluster-cq2hbvmifkaj.sa-east-1.rds.amazonaws.com
      - PG_PORT=5432
      - PG_DB=tax-engine-database-db-stage
      - PG_USER=tax_engine_database_stage
      - PG_PASSWORD=lia7Nie3bahch6teiyaeto5chie2yaiN
      - TABLE_NAME=exclusiones
      - COMMAND=init # use jupyter to start jupyter lab and run the app from there
      - JUPYTER_TOKEN=the5ooxoo0ahNoojuNgiahoon8koozie
      - CREATE=true # This variable is only necessary for local development
      - OUTPUT_PATH=/code/app/downloads
      - AGENTE=1
      - GRANT_TYPE=client_credentials
      - CLIENT_ID=iwmojaoson1dls1u9771lul9rc9uzlc7
      - CLIENT_SECRET=QuWrsUMhjrWUjwDtZ3ohjoXhMoGl8qfH
      - BOX_SUBJECT_ID=26053675872
      - BOX_SUBJECT_TYPE=user
      - BOX_ENV=DEV
      - INPUT_FOLDER_ID=https://app.box.com/s/m6tflakmt0ytdwxq299dq9596ijx8v6d
      - OUTPUT_FOLDER_ID=275038662740
      - MAIN_FOLDER_ID=275036558199
    ports:
      - "1022:22"
      - "3002:3002" # Debugpy if Debug=true | Matching the .vscode launch "debugServer": 3002 
      - "8888:8888"
    tty: true
    volumes:
      - ./:/code
networks:
  default:
      external:
        name: tax-engine-database_default
