---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: importar-clientes-cronjob
  namespace: jx-staging
spec:
  schedule: "11 */2 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: importar-clientes-cronjob
        spec:
          containers:
          - name: importar-clientes-bot
            image: "699339193037.dkr.ecr.sa-east-1.amazonaws.com/calyx-servicios/bots:arba-padron-ea68271-202208132337"
            imagePullPolicy: Always
            command:
              - "/etc/bootstrap.sh"
            env:
            - name: LOG_CONFIG_PATH
              value: "./app/logging.ini"
            - name: JSON_CONFIG_PATH
              value: "./app/txt/settings.json"
            - name: PG_HOST
              value: "taxengine-db"
            - name: PG_PORT
              value: "5432"
            - name: PG_DB
              value: "api"
            - name: PG_USER
              value: "api"
            - name: PG_PASSWORD
              value: "api"
            - name: CUIT
              value: "33629749859"
            - name: PASSWORD
              value: "041298"
            - name: RETRO
              value: "1"
            - name: COMMAND
              value: "init"
            resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
          restartPolicy: "Never"
