# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: QA Test

on:
  push:
    branches:
      - '*'

jobs:

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Black
        run: pip install git+https://github.com/psf/black
      - name: Run black --check .
        run: black --check -l 100 .

  flake8:
    needs: black
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install flake8
      - name: flake8
        run: |
          flake8 . --exclude=addons_external,*.pyc,.github,__init__.py --max-line-length=100 --extend-ignore=F401,F811,E203 --statistics

  pylint:
    needs: black
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pylint
      - name: PyLint
        run: |
          pylint ./**/*.py --rcfile ./config/pylint.cfg --fail-under 10 --ignore-patterns=.github --disable=W0718,E1101

